### PR TITLE
Renterd cluster

### PR DESCRIPTION
**Pull request by pcfreak30**

### CODE REVIEW

**Comment by pcfreak30** [comment]
digger plan

**Comment by ghost** [comment]
| Project | Status | Plan | + | ~ | - |
|---------|--------|------|---|---|---|
|:x: **test-cluster** |<a href='https://github.com/LumeWeb/test-cluster/actions/runs/11837378562'>failed</a> | <a href=''>Plan</a> | 0 | 0 | 0|

**Comment by ghost** [comment]
| Project | Status | Plan | + | ~ | - |
|---------|--------|------|---|---|---|
|:x: **test-cluster** |<a href='https://github.com/LumeWeb/test-cluster/actions/runs/11840414465'>failed</a> | <a href=''>Plan</a> | 0 | 0 | 0|

**Comment by ghost** [comment]
| Project | Status | Plan | + | ~ | - |
|---------|--------|------|---|---|---|
|:x: **test-cluster** |<a href='https://github.com/LumeWeb/test-cluster/actions/runs/11840499066'>failed</a> | <a href=''>Plan</a> | 0 | 0 | 0|

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by ghost** [comment]
:white_check_mark: Command unlock completed successfully

**Comment by pcfreak30** [comment]
digger apply

**Comment by ghost** [comment]
| Project | Status | Apply | + | ~ | - |
|---------|--------|------|---|---|---|
|:x: **test-cluster** |<a href='https://github.com/LumeWeb/test-cluster/actions/runs/11866644965'>failed</a> | <a href=''>Apply</a> | 0 | 0 | 0|

**Pull request merged**
